# Generated by Django 4.1 on 2023-01-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_from', models.CharField(max_length=50)),
                ('f_type', models.CharField(max_length=50)),
                ('f_subject', models.CharField(max_length=500)),
                ('f_content', models.CharField(max_length=500)),
                ('is_actioned', models.BooleanField(default=False)),
            ],
        ),
    ]
